### ISSUE TITLE
Mock-Ups

### ISSUE THREAD

**Issue by AmadeusGraves** [AmadeusGraves/ISPP#15]
**General**
Crear mock-ups de los casos de usos core, usando tecnologías como Balsamiq, Powerpoint, Marvel o Adobe.

!OJO¡: Los mock-ups deben ser interactivos.

**Comment by marmargal** [comment]
https://drive.google.com/drive/folders/1EDjev2uGebiR8VlI1MDT-ffpT_mCuG_i

**Comment by jualinfer** [comment]
All views done except:
- Payment view
- Route profile view (with variants depending on type of user logged, and route state)
- Links to move between views
