### ISSUE TITLE
Estudio de Mercado

### ISSUE THREAD

**Issue by AmadeusGraves** [AmadeusGraves/ISPP#17]
**General**
- Hacer estudio de mercado para el precio por kilómetro de la aplicación.
- Profundizar en el análisis de nuestros competidores.
- Dar solución al tema de la amortización, esto es, encontrar una forma de hacer nuestra app más barata que las empresas tipo Uber y Cabify de cara al que es llevado de un sitio a otro, y de forma que al conductor le sea rentable tener que llevar a gente.

**Comment by juaguecar** [comment]
Precio por kilometro de la aplicación: Carlos
Analisis competidores (emparejado con https://github.com/AmadeusGraves/ISPP/issues/17): Juancar, Jd
Solución amortización: Una vez tengamos toda la información necesaria hacemos una reunión rápida y pensamos como solucionarlo (Domingo?)
