### ISSUE TITLE
Legalidad Software

### ISSUE THREAD

**Issue by AmadeusGraves** [AmadeusGraves/ISPP#18]
**General**
Analizar cómo gestiona la competencia los temas legales para tomar decisiones.

**Comment by juaguecar** [comment]
-Como gestionan en caso de accidente
-Como gestionan conflictos
-Tema de seguros

**Comment by juaguecar** [comment]
Jd: Blablacar, Uber
Juancar: Amovens, Cabify
Mario: Carpooling Spain, Zitify
Angel: Analizar si existen mas competidores aparte de los mencionados.

**Comment by juaguecar** [comment]
https://docs.google.com/document/d/1QajE5mXv8YylP6Wi2TaPD3yNhK8PaZdmTmKSdJ_DQCE/edit

**Comment by jucansu** [comment]
Esta es la buena: 
https://drive.google.com/file/d/13uqB5PAiilgzIU2URVkEzo0kGP6fecB1/view?usp=sharing

**Comment by MarioShez** [comment]
Añadido el estudio sobre la legalidad de Carpooling Spain y Zityfy

**Comment by jucansu** [comment]
https://docs.google.com/document/d/1IASvL-LCtqEJj8MpFdhl2Qo2F_cekuASw6n2RT690p0/edit?usp=sharing

**Comment by juaguecar** [comment]
Añadido Blablacar y Uber

**Comment by juaguecar** [comment]
Definida legalidad.
