### ISSUE TITLE
Organización de Sprints y Metodología de Trabajo.

### ISSUE THREAD

**Issue by AmadeusGraves** [AmadeusGraves/ISPP#22]
**General**
Ver como nos organizamos en cuanto a aplicaciones de comunicación, etc.... Ademas de como nos organizaremos a lo largo de los Springs

**Comment by MarioShez** [comment]
Enlace al documento: https://docs.google.com/document/d/1l6d4h58Ijl6nUdVBMj8NO3gxNWqEfkwb_3wWpbbXhr8/edit?usp=sharing

**Comment by MarioShez** [comment]
Añadido al documento los diagramas de Gantt
