### ISSUE TITLE
Mejorar Mockups

### ISSUE THREAD

**Issue by AmadeusGraves** [AmadeusGraves/ISPP#23]
**General**
Corregir Mockups ademas de perfilarlos para que no muestra tanta información en una sola pantalla.

**Comment by marmargal** [comment]
https://drive.google.com/drive/folders/1gRaq_6SojrOlTIMGKtm5owhnRU9APo6J

**Comment by jualinfer** [comment]
Mockups finished.

**Comment by jualinfer** [comment]
Mockups updated, missing a few new views.

**Comment by jualinfer** [comment]
Added missing mockups.
