### ISSUE TITLE
Charter Commitment

### ISSUE THREAD

**Issue by AmadeusGraves** [AmadeusGraves/ISPP#28]
**General**
Realizar un documento en el que el equipo este de acuerdo en la realización de este proyecto.

El documento debe tener los siguientes apartados.
- Introducción: Breve descripción del producto software que queremos desarrollar.
- Riesgos que conlleva la realización de dicho proyecto.
- Firmas

Puede ver la información de los integrantes del equipo a través de este [Link](https://docs.google.com/document/d/1CnohWc5gxl-bylV3HdubcxK9ODZtgnaOB9GjnoHezrs/edit)

**Comment by JesusPerezCarmona** [comment]
No consigo encontrar una definición exacta de una Charter of Commitments, solo ejemplos de algunas empresas algo distintos unos de otros. Entiendo que el documento debe contener los compromisos del producto/servicio de la empresa, supongo. Parece algo distinto a lo que nos dijeron en que consistiría.

Ejemplos:
Urban Waste: http://www.urban-waste.eu/charter-of-commitments/
Mobiyo: https://www.mobiyo.com/commitment/
Melior: http://www.programmemelior.com/en/business/what-does-a-commitment-charter-entail/

Luego hay otra cosa llamada Team Charter, que no sé si es lo mismo o algo parecido o a lo mejor a lo que se referian los profesores.

Un par de definiciones:
https://www.smartsheet.com/essential-guide-creating-effective-team-chárter
https://thethrivingsmallbusiness.com/team-charter-statement-why-writing-a-team-charter-and-purpose-statement-is-important/
Y una plantilla de ejemplo: https://www.teamhelper.com/sample/TC_GuideSample.pdf

**Comment by JesusPerezCarmona** [comment]
Link al documento: https://docs.google.com/document/d/1Ykd3MfPQ9_zxFK0w486Hk7t9F3kSejTVzBIdtDjVgmk/edit
