### ISSUE TITLE
DAFO

### ISSUE THREAD

**Issue by AmadeusGraves** [AmadeusGraves/ISPP#29]
Realizar un DAFO sobre las debilidades y competencias del proyecto.

Si desea saber mas sobre DAFOs mire este [Link](https://www.sdelsol.com/blog/pymes/analisis-dafo/)

**Comment by marmargal** [comment]
https://docs.google.com/document/d/1Qy19WFUF7KrB3xhFcmrXNfK4TZ7ejka4B_UifAIwJM8/edit
