### ISSUE TITLE
Reorganizar Sprints

### ISSUE THREAD

**Issue by AmadeusGraves** [AmadeusGraves/ISPP#33]
**General**
- Añadir horas a los diagramas de gantts.
- Tabla de Persona/Tarea Desarrollo.
- Añadir al Sprint la tarea de recoger los feedbacks de los usuarios piloto.

**Comment by AmadeusGraves** [comment]
Cambios: 
- Se han añadido tareas nuevas.
- Se le han asignado un intervalo de tiempo a las tareas.
- Se ha organizado en grupos las tareas del sprint
- Se han generado las gráficas.

**Comment by jualinfer** [comment]
Task distribution per member instead of teams.

**Comment by carjimcor** [comment]
Modified tasks begin date.

**Comment by carjimcor** [comment]
The updated one is at ISPP/Semana 6/Sprint Planning

**Comment by jualinfer** [comment]
Changes to sprints planification and created resumed versions for presentation.
