### ISSUE TITLE
Grado de Innovación

### ISSUE THREAD

**Issue by AmadeusGraves** [AmadeusGraves/ISPP#4]
**General**
Explicar en caso de que existan soluciones software parecidas a nuestra propuesta, que tiene ademas nuestra propuesta para calificarla como "Rentable".

**Comment by JesusPerezCarmona** [comment]
Documento: https://docs.google.com/document/d/1aBwojZ_UoUsJ3fsCbxkXJCLIr-nMgi4_iXnFtrwmTbU/edit
