### ISSUE TITLE
Lista de Usuarios Piloto

### ISSUE THREAD

**Issue by AmadeusGraves** [AmadeusGraves/ISPP#5]
**General**
Posibles candidatos que estarían interesados en nuestra propuesta.

**Comment by juaguecar** [comment]
Conseguir el compromiso de 25-30 usuarios de ambos tipos (conductores y viajeros)

**Comment by juaguecar** [comment]
https://docs.google.com/spreadsheets/d/1U6HjnO8qGtFJZothsfkwYTRhnE-SpPTbtwduYpiwH5U/edit#gid=0

**Comment by juaguecar** [comment]
https://docs.google.com/spreadsheets/d/1ohf2kZalTDLa5U0PrVeSWSRho_edSIM5BoBKrv2sX70/edit#gid=0
