### ISSUE TITLE
Credentials Management

### ISSUE THREAD

**Issue by AmadeusGraves** [AmadeusGraves/ISPP#73]
**General**
Se realizara el cambio de credenciales en caso de que el usurario (Driver o Passerger) quiera cambiar de contraseña. 
Es una vista a parte del formulario de edicion del profile del usuario.

**Mockups**
![Edit credentials](https://user-images.githubusercontent.com/18572939/55413511-bcdc6c00-5569-11e9-9910-e61dc815b980.png)

**Importante**
En caso de duda preguntar el requirements engineer (Juanma).
Revisar el UML #34.

**Comment by MarioShez** [comment]
Funcionalidad implementada
