### ISSUE TITLE
Casos de Usos Core

### ISSUE THREAD

**Issue by AmadeusGraves** [AmadeusGraves/ISPP#8]
**General**
Casos de Usos que son imprescindibles puesto que muestran nuestra idea de negocio.

**Comment by jualinfer** [comment]
https://docs.google.com/document/d/1p-b9pPRN_nBqaj_2gzNw8Tfs_8NVqW0jRFSp0O8dUms/edit

**Comment by jualinfer** [comment]
User histories and user core cases added.
