### ISSUE TITLE
Documentación

### ISSUE THREAD

**Issue by AmadeusGraves** [AmadeusGraves/ISPP#88]
**General**
- En la documentación debe ir también el desglose completo de tareas, separado por semana 1 y semana 2, con sus deadlines, horas estimadas, etc; añadir las dos gráficas de tareas por miembro (semana 1 y semana 2) con sus correspondientes notas de rendimiento y total de horas dedicadas; una sección explicando la métrica de rendimiento
- Mejorar la explicación de cómo se ha calculado el presupuesto para el proyecto, mostrar la gráfica de gastos con su correspondiente explicación de por qué está como está, y otra gráfica que mida las tareas planeadas vs completadas para los sprints
- Incluir actas de reunión de sprint planning y sprint retrospective
- Volver a incluir en la documentación los enlaces a la app desplegada, a github y los nuevos credenciales (como el populate se genera automáticamente, puede que haya cambiado alguna cosa, además de que las claves han pasado a ser ahora "asd"

**Comment by AmadeusGraves** [comment]
Documento: [Google Drive](https://docs.google.com/document/d/1XCMWXlcvkyHFTQBpo2cS73ShtJIwjgPW0FnY4UM-bCI/edit?usp=sharing)

**Comment by JesusPerezCarmona** [comment]
Faltarían:

-Gráfica de costes hasta ahora
-Gráfica de rendimiento general hasta ahora (parecida a la de costes)
-Gráficas de rendimiento de cada miembro de la segunda semana
-Evaluación del plan de pilotaje
