### ISSUE TITLE
General Interface Remodeling

### ISSUE THREAD

**Issue by AmadeusGraves** [AmadeusGraves/ISPP#99]
**General**
- Añadir un Background
- Hacer una interfaz mas "Profesional"
- Investigar la posibilidad de incluir las rutas en Cajas 
- Retocar el Diseño del Header
- Internacionalizar Textos

**Comment by carjimcor** [comment]
Poner la parte de buscar ruta/publicar ruta mucho mas pequeña o quizas de otra forma, al ser estatico se ve excesivamente grande y poco bonito.
